### PR TITLE
spike an API client

### PR DESCRIPTION
**Pull request by jreut**

### CODE REVIEW

**Comment by Thrillberg** [comment]
@jreut I've filled in some of the blanks we left from last night. A few observations:
1) It loads in the browser!
2) The server errors when registering a new user
3) I'm passing the `client` differently, not injecting it but importing is. Izzat ok?
4) I have a Slack channel dedicated to Imperial where I've been chatting with Kieran and Anton about it. I presume you don't want to pollute your experience with Yet Another Slack Channel but I figured I'd offer to invite you if you're interested. We can totally keep communication to phone/GitHub, too, though!

**Comment by jreut** [comment]
> @jreut I've filled in some of the blanks we left from last night. A few observations:
> 
> 1. It loads in the browser!

Yay!

> 2. The server errors when registering a new user

Yay—hrm, what's the error?

> 3. I'm passing the `client` differently, not injecting it but importing is. Izzat ok?

I don't know! It depends on the semantics of `import` in whatever module loader system we have here. My completely unsubstantiated hunch is the module is only executed on first import and then reused on subsequent imports. If that's the case, this is definitely okay since there's only one WebSocket object ever in existence at a time.

> 4. I have a Slack channel dedicated to Imperial where I've been chatting with Kieran and Anton about it. I presume you don't want to pollute your experience with Yet Another Slack Channel but I figured I'd offer to invite you if you're interested. We can totally keep communication to phone/GitHub, too, though!

I have but one active Slack membership, and that's for work. Thank you for the invitation, but I must indeed decline!

**Comment by Thrillberg** [comment]
The user registration error is gone when I fixed the websocket header business! What does the "This change is Reviewable" button in your comment mean? Do you think there's anything more to do on this issue or should we review 'n' merge?

**Comment by jreut** [comment]
Reviewable is a tool my job uses for reviewing PRs. I didn't expect it to post that to other PRs; it might be a bug in the service.

And sure, let's merge this code! I'll leave the honor of pushing the button to you.

**Review by Thrillberg — APPROVED** [review]
Looks great! Added some cleanup and squarshed down to one commit.

**Pull request merged**
